name: peerdid
description: Dart implementation for PeerDID from identity.foundation specification
version: 0.0.3
homepage: https://github.com/ghabxph/dart_peerdid

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  crypto: ^2.1.5
  cryptography: ^1.4.1
  fast_base58: ^0.1.9
  uuid: ^2.2.2
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
